language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  - pip install -r requirements.txt

script:
  - set -e
  - ./run_cookiecutter_example.py
  - pip install -e example/
  - ./copy_user_content.sh
  - pytest example/
